import { jsPDF } from "jspdf";

/**
 * Normalizes Turkish characters for standard jsPDF fonts to avoid encoding rendering glitches.
 */
function sanitizeText(str) {
  if (!str) return "";
  const charMap = {
    'ğ': 'g', 'Ğ': 'G',
    'ü': 'u', 'Ü': 'U',
    'ş': 's', 'Ş': 'S',
    'ı': 'i', 'İ': 'I',
    'ö': 'o', 'Ö': 'O',
    'ç': 'c', 'Ç': 'C'
  };
  return String(str).replace(/[ğĞüÜşŞıİöÖçÇ]/g, (match) => charMap[match] || match);
}

/**
 * Formats date for display in PDF
 */
function formatDate(dateStr) {
  if (!dateStr) return "-";
  try {
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return dateStr;
    const day = String(d.getDate()).padStart(2, '0');
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const year = d.getFullYear();
    return `${day}.${month}.${year}`;
  } catch (e) {
    return dateStr;
  }
}

/**
 * Generates and downloads a PDF document for Flight or Hotel Reservation.
 */
export function generateReservationPdf({
  isFlight = false,
  pnrCode = "PNR-123456",
  itemTitle = "",
  destination = "",
  startDate = "",
  endDate = "",
  passengers = [],
  totalPrice = 0,
  currency = "TRY",
  userEmail = "",
  extraDetails = {},
  lang = "tr"
}) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const language = (lang || "tr").toLowerCase();

  const labels = {
    tr: {
      docTypeHotel: "Otel Rezervasyonu",
      docTypeFlight: "Uçuş Bileti",
      fileNameHotel: "Otel_Rezervasyon",
      fileNameFlight: "Bilet",
      titleSuffix: "Onay Belgesi",
      pnrLabel: "PNR / REZ. KODU",
      hotelPrefix: "Otel:",
      flightPrefix: "Ucus:",
      routeLocation: "Gidis / Varıs Lokasyonu:",
      location: "Lokasyon:",
      departureDate: "Kalkıs Tarihi:",
      returnDate: "Donus Tarihi:",
      checkIn: "Giris Tarihi:",
      checkOut: "Cıkıs Tarihi:",
      contactEmail: "İletisim E-Posta:",
      passengerInfo: "Yolcu Bilgileri",
      guestInfo: "Misafir Bilgileri",
      fullName: "Ad Soyad",
      idPassportNo: "T.C. / Pasaport No",
      type: "Tipi",
      adult: "Yetiskin",
      child: "Cocuk",
      guestFallback: "Misafir",
      paymentStatus: "Odeme Durumu: TAMAMLANDI",
      totalAmount: "Toplam Tutar:",
      footerNote: "Bu belge Sanny Travel tarafindan otomatik olarak olusturulmustur."
    },
    en: {
      docTypeHotel: "Hotel Booking",
      docTypeFlight: "Flight Ticket",
      fileNameHotel: "Hotel_Booking",
      fileNameFlight: "Ticket",
      titleSuffix: "Confirmation",
      pnrLabel: "PNR / BOOKING CODE",
      hotelPrefix: "Hotel:",
      flightPrefix: "Flight:",
      routeLocation: "Departure / Arrival Location:",
      location: "Location:",
      departureDate: "Departure Date:",
      returnDate: "Return Date:",
      checkIn: "Check-in Date:",
      checkOut: "Check-out Date:",
      contactEmail: "Contact Email:",
      passengerInfo: "Passenger Information",
      guestInfo: "Guest Information",
      fullName: "Full Name",
      idPassportNo: "ID / Passport No",
      type: "Type",
      adult: "Adult",
      child: "Child",
      guestFallback: "Guest",
      paymentStatus: "Payment Status: APPROVED",
      totalAmount: "Total Amount:",
      footerNote: "This document was automatically generated by Sanny Travel."
    },
    de: {
      docTypeHotel: "Hotelbuchung",
      docTypeFlight: "Flugticket",
      fileNameHotel: "Hotelbuchung",
      fileNameFlight: "Ticket",
      titleSuffix: "Bestatigung",
      pnrLabel: "PNR / BUCHUNGSCODE",
      hotelPrefix: "Hotel:",
      flightPrefix: "Flug:",
      routeLocation: "Abflug- / Ankunftsort:",
      location: "Standort:",
      departureDate: "Abflugdatum:",
      returnDate: "Ruckflugdatum:",
      checkIn: "Anreisedatum:",
      checkOut: "Abreisedatum:",
      contactEmail: "Kontakt-E-Mail:",
      passengerInfo: "Passagierinformationen",
      guestInfo: "Gasteinformationen",
      fullName: "Vollstandiger Name",
      idPassportNo: "Ausweis / Pass-Nr.",
      type: "Typ",
      adult: "Erwachsener",
      child: "Kind",
      guestFallback: "Gast",
      paymentStatus: "Zahlungsstatus: BESTATIGT",
      totalAmount: "Gesamtbetrag:",
      footerNote: "Dieses Dokument wurde automatisch von Sanny Travel erstellt."
    },
    ru: {
      docTypeHotel: "Bronirovanie otelya",
      docTypeFlight: "Aviabilet",
      fileNameHotel: "Otel_Bron",
      fileNameFlight: "Bilet",
      titleSuffix: "Podtverzhdenie",
      pnrLabel: "PNR / KOD BRONI",
      hotelPrefix: "Otel:",
      flightPrefix: "Reys:",
      routeLocation: "Marshrut / Lokatsiya:",
      location: "Lokatsiya:",
      departureDate: "Data vyleta:",
      returnDate: "Data obratnogo vyleta:",
      checkIn: "Data zaezda:",
      checkOut: "Data vyezda:",
      contactEmail: "Kontaktnyy Email:",
      passengerInfo: "Informatsiya o passazhirakh",
      guestInfo: "Informatsiya o gostyakh",
      fullName: "FIO",
      idPassportNo: "Pasport / Udostoverenie",
      type: "Tip",
      adult: "Vzroslyy",
      child: "Rebenok",
      guestFallback: "Gost",
      paymentStatus: "Status oplaty: PODTVERZHDENO",
      totalAmount: "Itogovaya summa:",
      footerNote: "Etot dokument byl avtomaticheski sgenerirovan Sanny Travel."
    }
  };

  const t = labels[language] || labels.tr;

  const pnr = pnrCode || extraDetails.reservationNumber || extraDetails.id || "PNR12345";
  const docType = isFlight ? t.docTypeFlight : t.docTypeHotel;
  const fileName = isFlight ? `${t.fileNameFlight}_${pnr}.pdf` : `${t.fileNameHotel}_${pnr}.pdf`;

  // Header Banner
  doc.setFillColor(30, 41, 59); // slate-800
  doc.rect(0, 0, 210, 35, "F");

  // Title inside Banner
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("SANNY TRAVEL", 15, 18);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(sanitizeText(`${docType} ${t.titleSuffix}`), 15, 26);

  // PNR Badge Box
  doc.setFillColor(59, 130, 246); // blue-500
  doc.roundedRect(140, 8, 55, 20, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(sanitizeText(t.pnrLabel), 145, 14);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(sanitizeText(pnr), 145, 23);

  let currentY = 45;
  const boxHeight = isFlight ? 50 : 54;

  // Reservation Details Card Box
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.setFillColor(248, 250, 252); // slate-50
  doc.roundedRect(15, currentY, 180, boxHeight, 3, 3, "FD");

  doc.setTextColor(15, 23, 42); // slate-900
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(sanitizeText(isFlight ? `${t.flightPrefix} ${itemTitle}` : `${t.hotelPrefix} ${itemTitle}`), 20, currentY + 9);

  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105); // slate-600

  if (isFlight) {
    const flightNo = extraDetails.flightNumber || extraDetails.flightNo || "TK-2412";
    const ticketClass = extraDetails.ticketClass || extraDetails.flightClass || "Economy";
    const baggage = extraDetails.baggageAllowance || extraDetails.baggage || "20 kg Bagaj";
    const depTime = extraDetails.departureTime || "14:30";
    const arrTime = extraDetails.arrivalTime || "16:15";

    doc.text(sanitizeText(`Ucus No: ${flightNo}`), 20, currentY + 17);
    doc.text(sanitizeText(`Sinif / Bagaj: ${ticketClass} | ${baggage}`), 110, currentY + 17);
    doc.text(sanitizeText(`${t.routeLocation} ${destination || '-'}`), 20, currentY + 25);
    doc.text(sanitizeText(`${t.departureDate} ${formatDate(startDate)} (${depTime})`), 20, currentY + 33);
    if (endDate || arrTime) {
      doc.text(sanitizeText(`Varis Saati: ${arrTime}`), 110, currentY + 33);
    }
    doc.text(sanitizeText(`${t.contactEmail} ${userEmail || '-'}`), 20, currentY + 41);
  } else {
    const roomType = extraDetails.roomType || "Standard Oda";
    const boardType = extraDetails.boardType || "Her Sey Dahil";
    const checkInTime = extraDetails.checkInTime || "14:00";
    const checkOutTime = extraDetails.checkOutTime || "12:00";
    const nights = extraDetails.nights || (startDate && endDate ? Math.max(1, Math.round((new Date(endDate) - new Date(startDate)) / (1000 * 60 * 60 * 24))) : 1);

    doc.text(sanitizeText(`Oda & Pansiyon: ${roomType} / ${boardType}`), 20, currentY + 17);
    doc.text(sanitizeText(`Toplam Gece: ${nights} Gece`), 125, currentY + 17);
    doc.text(sanitizeText(`${t.location} ${destination || '-'}`), 20, currentY + 25);
    doc.text(sanitizeText(`${t.checkIn} ${formatDate(startDate)} (${checkInTime})`), 20, currentY + 33);
    doc.text(sanitizeText(`${t.checkOut} ${formatDate(endDate || startDate)} (${checkOutTime})`), 110, currentY + 33);
    doc.text(sanitizeText(`${t.contactEmail} ${userEmail || '-'}`), 20, currentY + 42);
  }

  currentY += boxHeight + 8;

  // Passenger / Guest Details Section
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(sanitizeText(isFlight ? t.passengerInfo : t.guestInfo), 15, currentY);

  currentY += 5;

  // Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(15, currentY, 180, 8, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(51, 65, 85);
  doc.text("#", 18, currentY + 5.5);
  doc.text(sanitizeText(t.fullName), 30, currentY + 5.5);
  doc.text(sanitizeText(t.idPassportNo), 95, currentY + 5.5);
  doc.text(sanitizeText(t.type), 155, currentY + 5.5);

  currentY += 8;

  const passList = passengers && passengers.length > 0 ? passengers : [
    {
      firstName: extraDetails.firstName || t.guestFallback,
      lastName: extraDetails.lastName || "",
      identityNumber: extraDetails.tcNo || extraDetails.identityNumber || "-",
      type: "ADULT"
    }
  ];

  passList.forEach((p, idx) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(30, 41, 59);

    const name = `${p.firstName || ''} ${p.lastName || ''}`.trim() || "-";
    const tcNo = p.identityNumber || p.tcNo || p.passportNumber || "-";
    const typeLabel = p.type === "CHILD" ? t.child : t.adult;

    doc.text(String(idx + 1), 18, currentY + 6);
    doc.text(sanitizeText(name), 30, currentY + 6);
    doc.text(sanitizeText(tcNo), 95, currentY + 6);
    doc.text(sanitizeText(typeLabel), 155, currentY + 6);

    doc.setDrawColor(241, 245, 249);
    doc.line(15, currentY + 9, 195, currentY + 9);

    currentY += 10;
  });

  currentY += 10;

  // Payment Summary Box
  doc.setFillColor(240, 253, 244); // emerald-50
  doc.setDrawColor(187, 247, 208); // emerald-200
  doc.roundedRect(15, currentY, 180, 22, 3, 3, "FD");

  doc.setTextColor(22, 101, 52); // emerald-800
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(sanitizeText(t.paymentStatus), 22, currentY + 9);

  doc.setFontSize(13);
  doc.text(sanitizeText(`${t.totalAmount} ${Math.round(totalPrice || 0).toLocaleString("tr-TR")} ${currency}`), 110, currentY + 14);

  // Footer Note
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text(sanitizeText(t.footerNote), 105, 285, { align: "center" });

  doc.save(fileName);
}
